@@startuml

actor dev

rectangle "Github" {
    rectangle "Frontend Repo"
    rectangle "Backend Repo"
    rectangle cicd_Repo [
        cicd repo
        ---
         ㄴ.github/workflows/deploy.yml
         ㄴ/docker-compose.yml
    ]

    "Frontend Repo" --[#Red]> cicd_Repo : 3. image tag change and action trigger 
    "Backend Repo" --[#Red]> cicd_Repo : 3. image tag change and action trigger
}

cloud "Azure" {
    rectangle "ACR" {
        rectangle "Frontend-ACR"
        rectangle "Backend-ACR"
    }

    rectangle "Azure VM" {
        rectangle "docker-compose" {
            rectangle "frontend container"
            rectangle "backend container"
        }
    }
}

dev --[#Red]> "Frontend Repo" : 1. main branch push (Github Actions Trigger)
dev --[#Red]> "Backend Repo" : 1. main branch push (Github Actions Trigger)

"Frontend Repo" ---[#Red]> "Frontend-ACR" : 2. image upload
"Backend Repo" ---[#Red]> "Backend-ACR" : 2. image upload

"cicd_Repo" --[#Blue]> "Azure VM" : Github Actions Trigger

"frontend container" --[#Blue]> "frontend container" : 4. run script(git pull & docker-compose up)
"backend container" --[#Blue]> "backend container" : 4. run script(git pull & docker-compose up)

@@enduml