version: '3.8'

services:
  frontend:
    image: arctestsa.azurecr.io/frontend:3f3c1dff9de3f35700cff213770e561bae7b4d0f
    ports:
      - 80:80
    restart: always
  
  backend:
    image: arctestsa.azurecr.io/backend:v0.2
    ports:
      - 8000:8000
    restart: always
    environment:
      - API_MODE=${API_MODE}