version: '3.8'

services:
  frontend:
    container_name: frontend
    image: arctestsa.azurecr.io/frontend:d3f81f4fde77b8de14769ffbbafdbb725944d5ed
    ports:
      - 80:80
  
  backend:
    container_name: backend
    image: arctestsa.azurecr.io/backend:${BACKEND_TAG}
    ports:
      - 8000:8000
    
