version: '3.8'

services:
  frontend:
    container_name: frontend
    image: arctestsa.azurecr.io/frontend:97a85e4b46f2e26317a57f30e2f41f76b49f5efb
    ports:
      - 80:80
    restart: always
  
  backend:
    container_name: backend
    image: arctestsa.azurecr.io/backend:v0.1
    ports:
      - 8000:8000
    restart: always