version: '3.8'

services:
  frontend:
    image: arctestsa.azurecr.io/frontend:d9cf0afd98ee0cc452d040320252918a230516d6

    ports:
      - 80:80
    restart: always
  
  backend:
    image: arctestsa.azurecr.io/backend:${backend_tag}
    ports:
      - 8000:8000
    restart: always