version: '3.8'

services:
  frontend:
    container_name: frontend
    image: arctestsa.azurecr.io/frontend:f9c4b9d22b34c75d0a6c425293f4e51fe0a444df
    ports:
      - 80:80
    restart: always
  
  backend:
    container_name: backend
    image: arctestsa.azurecr.io/backend:v0.1
    ports:
      - 8000:8000
    restart: always