version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:d341c7f56bd05b26996dad94f3c4a7fddff8a18f
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:cf1abee68c01094628260b9c9f968ad87c72bddd
    ports:
      - 8000:8000
    restart: always
