version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:d341c7f56bd05b26996dad94f3c4a7fddff8a18f
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:bdb412e48371be4c706eacf51342973b7a4994ef
    ports:
      - 8000:8000
    restart: always
