version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:0.1.0
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: mlregistrytest.azurecr.io/test-backend:1.3.0
    ports:
      - 8000:8000
    restart: always
    env_file:
      - /home/azureuser/cicd/resources/.env
