version: '3.8'

services:
  frontend:
    container_name: frontend
    image: arctestsa.azurecr.io/frontend:406e1e12c69a4746e527642b6ddd179c0a28690b
    ports:
      - 80:80
    restart: always
  
  backend:
    container_name: backend
    image: arctestsa.azurecr.io/backend:v0.1
    ports:
      - 8000:8000
    restart: always