version: '3.8'

services:
  frontend:
    image: arctestsa.azurecr.io/frontend:e82ffeede7126bf9eb6fe29cb898234f101e25f2

    ports:
      - 80:80
    restart: always
  
  backend:
    image: arctestsa.azurecr.io/backend:v0.2
    ports:
      - 8000:8000
    restart: always