version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:d341c7f56bd05b26996dad94f3c4a7fddff8a18f
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:e5094b02080965823cdddb4cb34d4ac18baf55a2
    ports:
      - 8000:8000
    restart: always
