version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:96565f2c157eb5e3b8fcf30c304aace6fb7df1a7
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:6e4d2f581f17d20c1d2d021d6e969648005c9500
    ports:
      - 8000:8000
    restart: always
    env_file:
      - /home/azureuser/cicd/resources/.env
