version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:b8be5a4edc8a072e931147b9b55b4f5824e1797a
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:0.0.3-pre.7ad36fc
    ports:
      - 8000:8000
    restart: always
    env_file:
      - /home/azureuser/cicd/resources/.env
