version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:0.0.1
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:bcc904ea38b7ebcfd08dc092a0ffd00b46d19572
    ports:
      - 8000:8000
    restart: always
    env_file:
      - /home/azureuser/cicd/resources/.env
