version: '3.8'

services:
  frontend:
    container_name: frontend
    image: arctestsa.azurecr.io/frontend:ef05af6882f627a1667f785b93553fddda0c30cc
    ports:
      - 80:80
    restart: always
  
  backend:
    container_name: backend
    image: arctestsa.azurecr.io/backend:7b840969017abbf9d87aa068a0321dc9cc40abc2
    ports:
      - 8000:8000
    restart: always
    
