version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:0.1.0
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:bfd96d938c13bb9f76d583b8d8ffb84f1232dbcb
    ports:
      - 8000:8000
    restart: always
    env_file:
      - /home/azureuser/cicd/resources/.env
