version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:4407a7132c948d23fdebe98ba19232fb4e44ce32
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:1.0.4
    ports:
      - 8000:8000
    restart: always
    env_file:
      - /home/azureuser/cicd/resources/.env
