version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:96565f2c157eb5e3b8fcf30c304aace6fb7df1a7
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:dba53139de6384f00c32b08973ba2377a69138ba
    ports:
      - 8000:8000
    restart: always
    env_file:
      - /home/azureuser/cicd/resources/.env
