version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:0.1.0
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:c48ebe394ca3c0e089dc3e40004b5389d541796e
    ports:
      - 8000:8000
    restart: always
    env_file:
      - /home/azureuser/cicd/resources/.env
