version: '3.8'

services:
  frontend:
    container_name: frontend
    image: arctestsa.azurecr.io/frontend:d3f81f4fde77b8de14769ffbbafdbb725944d5ed
    ports:
      - 80:80
  
  backend:
    container_name: backend
    image: arctestsa.azurecr.io/backend:1ada06f93ff09d22177e2ad9457d374be1dba4d2
    ports:
      - 8000:8000
    
