version: '3.8'

services:
  frontend:
    image: arctestsa.azurecr.io/frontend:2687cf2ef1d10003ced4895eaf94caa2f30aba86

    ports:
      - 80:80
    restart: always
  
  backend:
    image: arctestsa.azurecr.io/backend:${backend_tag}
    ports:
      - 8000:8000
    restart: always