version: '3.8'

services:
  nginx:
    image: arctestsa.azurecr.io/frontend:0.1.0
    ports:
      - 80:80
    restart: always
  
  croft-api-server:
    image: arctestsa.azurecr.io/backend:b2dd8926d54288f032bd227c5cb238b2d3cff8ab
    ports:
      - 8000:8000
    restart: always
    env_file:
      - /home/azureuser/cicd/resources/.env
