name: Deploy to Azure VM

on:
    push:
        paths:
            - 'resources/**'
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Deploy
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  az acr login --name ${{ secrets.ACR_REGISTRY }} --username ${{ secrets.ACR_USERNAME }} --password ${{ secrets.ACR_PASSWORD }}
                  if [ -d '/home/azureuser/cicd' ]; then
                    echo "Directory exits"
                    cd /home/azureuser/cicd
                    git pull 
                    cd resources
                    docker compose up -d
                  else
                    echo "Directory does not exist"
                    git clone https://${{ secrets.PAT }}@github.com/${{ github.repository }}.git /home/azureuser/cicd
                    cd /home/azureuser/cicd/resources
                    docker compose up -d
                  fi
                