name: Deploy to Azure VM

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Setup SSH
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
                chmod 600 ssh_key.pem
            
            - name: Deploy to Azure VM
              run: |
                ssh -i ssh_key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "mkdir -p /home/azureuser/cicd"

                rsync -avz -e "ssh -i sua-vm_key.pem -o StrictHostKeyChecking=no" ./resources/docker-compose.yml azureuser@40.82.144.200:/home/azureuser/cicd

                ssh -i ssh_key.pem -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
                  cd /home/azureuser/cicd
                  docker compose up -d
                EOF
