name: Deploy to Azure VM

on:
    workflow_dispatch:
        inputs:
            continue:
                description: 'Do you want to continue?'
                required: true
                default: 'yes'

jobs:
    notify:
        runs-on: ubuntu-latest

        steps:
            - name: Send Slack Notification
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
              run: |
                if [ "${{ github.event.inputs.continue }}" == "yes" ]; then
                  curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment will continue."}' $SLACK_WEBHOOK_URL
                else
                  curl -X POST -H 'Content-type: application/json' --data '{"text":"Deployment has been halted by the user."}' $SLACK_WEBHOOK_URL
                  exit 1
                fi
    
    deploy:
        runs-on: ubuntu-latest
        needs: notify

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2