name: Rollback Workflow

on:
    workflow_dispatch:
        inputs:
            frontend_tag:
                description: 'Frontend tag'
                required: true
            backend_tag:
                description: 'Backend tag'
                required: true


jobs:
    rollback:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Checkout Input
              run: |
                echo "Frontend tag: ${{ github.event.inputs.frontend_tag }}"
                echo "Backend tag: ${{ github.event.inputs.backend_tag }}"

            - name: Get Image Info
              id: image_info
              run : |
                FRONTEND_IMAGE=$(grep 'image: arctestsa.azurecr.io/frontend:' resources/docker-compose.yml | awk -F: '{print $3}')
                BACKEND_IMAGE=$(grep 'image: arctestsa.azurecr.io/backend:' resources/docker-compose.yml | awk -F: '{print $3}')
                echo "::set-output name=frontend_image::$FRONTEND_IMAGE"
                echo "::set-output name=backend_image::$BACKEND_IMAGE"
            
            - name: Confirm Rollback Image tags
              run: |
                if dpkg --compare-versions "${{ github.event.inputs.frontend_tag }}" lt "${{ steps.image_info.outputs.frontend_image}}"; then
                    echo "Delete frontend image"
                    sed -i '/frontend:/,/backend:/{s|image: arctestsa.azurecr.io/frontend:.*|image: arctestsa.azurecr.io/frontend:'"${{ github.event.inputs.frontend_tag }}"'|}' resources/docker-compose.yml
                fi
                if dpkg --compare-versions "${{ github.event.inputs.backend_tag }}" lt "${{ steps.image_info.outputs.backend_image}}"; then
                    echo "Delete backend image"
                    sed -i '/croft-api-server:/,/restart: always/{s|image: arctestsa.azurecr.io/backend:.*|image: arctestsa.azurecr.io/backend:'"${{ github.event.inputs.backend_tag }}"'|}' resources/docker-compose.yml
                fi
                cat resources/docker-compose.yml