name: Rollback Workflow

on:
    workflow_dispatch:
        inputs:
            frontend_tag:
                description: 'Frontend tag'
                required: true
                type: choice
                options:
                  - 0.1.0
                  - 0.1.1
                  - 0.1.2
            backend_tag:
                description: 'Backend tag'
                required: true


jobs:
    rollback:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                repository: 'Suah-Cho/cicd'
                ref: ${{github.ref}}
                token: ${{ secrets.PAT }}

            - name: Checkout Input
              run: |
                echo "Frontend tag: ${{ github.event.inputs.frontend_tag }}"
                echo "Backend tag: ${{ github.event.inputs.backend_tag }}"

            - name: Get Image Info
              id: image_info
              run : |
                echo ${GITHUB_REF#refs/heads/}
                FRONTEND_IMAGE=$(grep 'image: arctestsa.azurecr.io/frontend:' resources/docker-compose.yml | awk -F: '{print $3}')
                BACKEND_IMAGE=$(grep 'image: arctestsa.azurecr.io/backend:' resources/docker-compose.yml | awk -F: '{print $3}')
                echo "frontend_image=$FRONTEND_IMAGE" >> "$GITHUB_OUTPUT"
                echo "backend_image=$BACKEND_IMAGE" >> "$GITHUB_OUTPUT"

            - name: Confirm Rollback Image tags and Delete Image
              run: |
                if dpkg --compare-versions "${{ github.event.inputs.frontend_tag }}" lt "${{ steps.image_info.outputs.frontend_image}}"; then
                    sed -i '/frontend:/,/backend:/{s|image: arctestsa.azurecr.io/frontend:.*|image: arctestsa.azurecr.io/frontend:'"${{ github.event.inputs.frontend_tag }}"'|}' resources/docker-compose.yml
                fi
                if dpkg --compare-versions "${{ github.event.inputs.backend_tag }}" lt "${{ steps.image_info.outputs.backend_image}}"; then
                    sed -i '/croft-api-server:/,/restart: always/{s|image: arctestsa.azurecr.io/backend:.*|image: arctestsa.azurecr.io/backend:'"${{ github.event.inputs.backend_tag }}"'|}' resources/docker-compose.yml
                fi
                cat resources/docker-compose.yml

            - name: Commit and Push Image Manifest File
              run: |
                git config user.email "sacho0929@gmail.com"
                git config user.name "Suah-Cho"
                git commit -am "Rollback frontend to ${{ github.event.inputs.frontend_tag }} and backend to ${{ github.event.inputs.backend_tag }}"
                git push origin ${GITHUB_REF#refs/heads/}

            - name: Notify message to Slack
              if: failure()
              uses: rtCamp/action-slack-notify@v2
              env:
                SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
                SLACK_CHANNEL: "github-actions-results"
                SLACK_COLOR: "green"
                SLACK_USERNAME: "Github CD"
                SLACK_ICON: ":rocket:"
                SLACK_TITLE: "ROLLBACK"
                SLACK_MESSAGE: ":rocket: Rollback Result: ${{ job.status }}\nRollback을 실패했습니다. 로그를 확인해주세요.\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
