name: Rollback Workflow

on:
    workflow_dispatch:
        inputs:
            frontend_tag:
                description: 'Frontend tag'
                required: true
            backend_tag:
                description: 'Backend tag'
                required: true

jobs:
    rollback:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Checkout Input
              run: |
                echo "Frontend tag: ${{ github.event.inputs.frontend_tag }}"
                echo "Backend tag: ${{ github.event.inputs.backend_tag }}"

            - name: Get Image Info
              id: image_info
              run : |
                FRONTEND_IMAGE=$(grep 'image: arctestsa.azurecr.io/frontend:' resources/docker-compose.yml | awk -F: '{print $3}')
                BACKEND_IMAGE=$(grep 'image: arctestsa.azurecr.io/backend:' resources/docker-compose.yml | awk -F: '{print $3}')
                echo "Frontend Image: $FRONTEND_IMAGE"
                echo "Backend Image: $BACKEND_IMAGE"
                
              
            