name: Rollback - Delete ACR image

on:
    workflow_dispatch:
        inputs:
            frontend_tag:
                description: 'Frontend tag'
                required: true
            backend_tag:
                description: 'Backend tag'
                required: true
            frontend_rollback:
                description: 'Frontend rollback'
                required: true
            backend_rollback:
                description: 'Backend rollback'
                required: true

jobs:
    rollback:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Input
              run: |
                echo "Frontend tag: ${{ github.event.inputs.frontend_tag }}"
                echo "Backend tag: ${{ github.event.inputs.backend_tag }}"
                echo "Frontend rollback: ${{ github.event.inputs.frontend_rollback }}"
                echo "Backend rollback: ${{ github.event.inputs.backend_rollback }}"